import { ACCEPTED_FILE_TYPES, FILE_EXTENSIONS, MAX_FILE_BYTES, MAX_FILES, MAX_TOTAL_BYTES, QUOTE_DESCRIPTION_MAX, QUOTE_DESCRIPTION_MIN, STEP_KEYS, type QuoteStep } from "./constants";
import type { QuoteDraft } from "./types";
export type QuoteError = "required" | "invalid_email" | "invalid_phone" | "description_short" | "description_long" | "invalid_number" | "budget_range" | "consent_required" | "file_type" | "file_size" | "file_count" | "file_total";
export type QuoteErrors = Record<string, QuoteError>;
const blank = (v: string) => !v.trim();
export const validEmail = (v: string) => /^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/.test(v.trim());
export const validPhone = (v: string) => /^\+?\d{6,15}$/.test(v.trim().replace(/[\s().-]/g, ""));
export const normalizePhone = (v: string) => v.trim().replace(/[\s().-]/g, "");
export function validateQuoteStep(step: QuoteStep, d: QuoteDraft): QuoteErrors { const e: QuoteErrors = {};
  if(step==="project"){if(blank(d.project.title))e["project.title"]="required";if(!d.project.type)e["project.type"]="required";if(d.project.description.trim().length<QUOTE_DESCRIPTION_MIN)e["project.description"]="description_short";else if(d.project.description.length>QUOTE_DESCRIPTION_MAX)e["project.description"]="description_long";if(!d.project.stage)e["project.stage"]="required";if(!d.project.objective)e["project.objective"]="required";if(!d.project.requesterType)e["project.requesterType"]="required";}
  if(step==="property"){if(!d.property.type)e["property.type"]="required";if(!d.property.use)e["property.use"]="required";if(!d.property.area)e["property.area"]="required";else if(Number(d.property.area)<=0)e["property.area"]="invalid_number";if(!d.property.condition)e["property.condition"]="required";if(!d.property.authorized)e["property.authorized"]="required";}
  if(step==="trades"){if(!d.trades.primary)e["trades.primary"]="required";if(d.trades.primary==="other"&&blank(d.trades.other))e["trades.other"]="required";}
  if(step==="finishes"){if(!d.finishes.level)e["finishes.level"]="required";if(!d.finishes.supplyMode)e["finishes.supplyMode"]="required";}
  if(step==="budget"){if(!d.budget.range)e["budget.range"]="required";if(d.budget.min&&Number(d.budget.min)<0)e["budget.min"]="invalid_number";if(d.budget.max&&Number(d.budget.max)<0)e["budget.max"]="invalid_number";if(d.budget.min&&d.budget.max&&Number(d.budget.max)<Number(d.budget.min))e["budget.max"]="budget_range";}
  if(step==="location"){if(blank(d.location.region))e["location.region"]="required";if(blank(d.location.city))e["location.city"]="required";if(blank(d.location.address))e["location.address"]="required";}
  if(step==="contact"){if(blank(d.contact.firstName))e["contact.firstName"]="required";if(blank(d.contact.lastName))e["contact.lastName"]="required";if(!validEmail(d.contact.email))e["contact.email"]="invalid_email";if(!validPhone(d.contact.phone))e["contact.phone"]="invalid_phone";if(!d.contact.whatsappSame&&d.contact.whatsapp&&!validPhone(d.contact.whatsapp))e["contact.whatsapp"]="invalid_phone";if(!d.contact.language)e["contact.language"]="required";if(!d.contact.preferredContact)e["contact.preferredContact"]="required";for(const k of ["acceptTerms","acceptPrivacy","confirmAccuracy","allowSharing","allowContact"] as const)if(!d.contact[k])e[`contact.${k}`]="consent_required";}
  return e; }
export const validateQuote = (d: QuoteDraft) => Object.assign({}, ...STEP_KEYS.map(s=>validateQuoteStep(s,d)));
export function validateQuoteFiles(files: File[]){const errors:{name:string;code:QuoteError}[]=[];if(files.length>MAX_FILES)errors.push({name:"",code:"file_count"});if(files.reduce((n,f)=>n+f.size,0)>MAX_TOTAL_BYTES)errors.push({name:"",code:"file_total"});for(const f of files.slice(0,MAX_FILES)){const ext=f.name.toLowerCase().slice(f.name.lastIndexOf("."));if(!(ACCEPTED_FILE_TYPES as readonly string[]).includes(f.type)||!FILE_EXTENSIONS[f.type]?.includes(ext))errors.push({name:f.name,code:"file_type"});else if(f.size>MAX_FILE_BYTES)errors.push({name:f.name,code:"file_size"});}return errors;}
export function normalizeQuote(d:QuoteDraft):QuoteDraft{return {...d,contact:{...d.contact,firstName:d.contact.firstName.trim(),lastName:d.contact.lastName.trim(),email:d.contact.email.trim().toLowerCase(),phone:normalizePhone(d.contact.phone),whatsapp:d.contact.whatsappSame?normalizePhone(d.contact.phone):normalizePhone(d.contact.whatsapp)},project:{...d.project,title:d.project.title.trim(),description:d.project.description.trim()},location:{...d.location,address:d.location.address.trim()}};}
